/** Types for the Electron preload bridge (implemented in preload.cjs). */

export type MediaSource = {
  id: string;
  name: string;
  path: string;
  kind: string;
  hasDicom: boolean;
  platform: string;
};

export type PacsConnection = {
  host: string;
  port: number;
  callingAe: string;
  calledAe: string;
  localAe?: string;
  localPort?: number;
};

export type PacsQueryLevel = 'study' | 'series' | 'instance';

export type PacsFindQuery = {
  level?: PacsQueryLevel;
  patientId?: string;
  patientName?: string;
  studyDate?: string;
  accession?: string;
  modality?: string;
  studyInstanceUID?: string;
  seriesInstanceUID?: string;
};

/** Unified C-FIND hit (study / series / instance). */
export type PacsHit = {
  level: PacsQueryLevel;
  patientId: string;
  patientName: string;
  studyDate: string;
  studyDescription: string;
  accessionNumber: string;
  modalities: string;
  modality: string;
  studyInstanceUID: string;
  seriesInstanceUID: string;
  sopInstanceUID: string;
  seriesDescription: string;
  seriesNumber: string;
  instanceNumber: string;
  seriesCount: string;
  instanceCount: string;
};

/** @deprecated use PacsHit */
export type PacsStudyHit = PacsHit;

export type PacsRetrieveOpts = {
  level?: PacsQueryLevel;
  seriesInstanceUid?: string;
  sopInstanceUid?: string;
  /** Pre-generated by renderer so progress/cancel can match before invoke resolves. */
  jobId?: string;
};

export type PacsRetrieveResult = {
  ok: boolean;
  files: string[];
  extractDir?: string;
  error?: string;
  cancelled?: boolean;
  jobId?: string;
};

export type ZipExtractResult =
  | { ok: true; files: string[]; extractDir: string; entryCount: number }
  | { ok: false; error: string; code?: string };

export type SaveFileDialogOptions = {
  title?: string;
  defaultPath?: string;
  filters?: Array<{ name: string; extensions: string[] }>;
};

export type OpenFileDialogOptions = {
  title?: string;
  filters?: Array<{ name: string; extensions: string[] }>;
};

export type SaveDirectoryDialogOptions = {
  title?: string;
  defaultPath?: string;
};

export type PacsRetrieveProgress = {
  jobId: string;
  received: number;
};

export type SliceApi = {
  openFolder: () => Promise<string | null>;
  openZipDialog: () => Promise<string | null>;
  openFileDialog: (opts?: OpenFileDialogOptions) => Promise<string | null>;
  /** Multi-select DICOM files from Explorer-style dialog. */
  openDicomFilesDialog: () => Promise<string[]>;
  openPath: (filePath: string) => Promise<string>;
  saveFileDialog: (opts?: SaveFileDialogOptions) => Promise<string | null>;
  saveDirectoryDialog: (opts?: SaveDirectoryDialogOptions) => Promise<string | null>;
  listDicomFiles: (folderPath: string) => Promise<string[]>;
  findDicomdir: (folderPath: string) => Promise<string | null>;
  resolveDroppedPaths: (
    paths: string[],
  ) => Promise<{ needsPassword: boolean; zipPath?: string; files: string[] }>;
  readFile: (filePath: string) => Promise<ArrayBuffer>;
  writeFile: (
    filePath: string,
    data: ArrayBuffer | Uint8Array,
  ) => Promise<{ ok: boolean; bytes: number; error?: string }>;
  writeTemp: (
    fileName: string,
    data: ArrayBuffer | Uint8Array,
  ) => Promise<{ ok: boolean; path?: string; bytes?: number; error?: string }>;
  zipNeedsPassword: (zipPath: string) => Promise<boolean>;
  extractZip: (zipPath: string, password?: string) => Promise<ZipExtractResult>;
  listMedia: () => Promise<MediaSource[]>;
  pacsEcho: (
    conn: PacsConnection,
  ) => Promise<{ ok: boolean; status?: number; error?: string }>;
  pacsFind: (
    conn: PacsConnection,
    query: PacsFindQuery,
  ) => Promise<{ ok: boolean; results: PacsHit[]; error?: string }>;
  pacsMove: (
    conn: PacsConnection,
    studyInstanceUid: string,
    opts?: PacsRetrieveOpts,
  ) => Promise<PacsRetrieveResult>;
  pacsGet: (
    conn: PacsConnection,
    studyInstanceUid: string,
    opts?: PacsRetrieveOpts,
  ) => Promise<PacsRetrieveResult>;
  pacsStore: (
    conn: PacsConnection,
    filePaths: string[],
  ) => Promise<{ ok: boolean; stored?: number; failed?: number; total?: number; error?: string }>;
  pacsRetrieveCancel: (jobId: string) => Promise<{ ok: boolean }>;
  onPacsRetrieveProgress: (cb: (p: PacsRetrieveProgress) => void) => () => void;
  getPacsProfiles: () => Promise<PacsProfilesPayload | null>;
  setPacsProfiles: (payload: PacsProfilesPayload) => Promise<{ ok: boolean; error?: string }>;
  /** Taskbar/dock progress 0–1, or -1 / null to clear. */
  setProgressBar: (value: number) => void;
  onAppCommand: (
    cb: (payload: { command: string; payload?: unknown }) => void,
  ) => () => void;
  onOpenPaths: (cb: (paths: string[]) => void) => () => void;
  getPathForFile: (file: File) => string;
  getAppVersion: () => Promise<string>;
  getUpdateRepo: () => Promise<{ owner: string; repo: string }>;
  checkUpdate: () => Promise<
    | {
        status: 'up-to-date';
        currentVersion: string;
        latestVersion: string;
      }
    | {
        status: 'available';
        currentVersion: string;
        latestVersion: string;
        releaseName: string;
        body: string;
        htmlUrl: string;
        downloadUrl: string | null;
        publishedAt: string | null;
      }
    | {
        status: 'error';
        currentVersion: string;
        message: string;
      }
  >;
  openExternal: (url: string) => Promise<{ ok: boolean; error?: string }>;
};

export type PacsProfilesPayload = {
  profiles: Array<{ id: string; name: string; conn: PacsConnection }>;
  activeId: string;
};
